### ISSUE TITLE
For the pre-trained model

### ISSUE THREAD

**Issue by huyle73** [diaoquesang/BS-LDM#2]
Would you mind if you can give to me the pre-trained model which you used to train from your dataset, please? I want to see the performance for that. Thank you very much.

**Comment by diaoquesang** [comment]
Sorry, we can only provide training code and detailed experimental descriptions for training BS-LDM currently, instead of pre-trained models.

**Comment by diaoquesang** [comment]
Now the pre-trained models are provided.
